

### Author
### Every Author, with their Books
GET http://localhost:8080/api/v1/authors/books
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Single Author with their Books
GET http://localhost:8080/api/v1/authors/1/books
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Every Author without their Books
GET http://localhost:8080/api/v1/authors
Authorization: Bearer PASTE_YOUR_TOKEN_HERE


### Single Author without Books
GET http://localhost:8080/api/v1/authors/2
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Create Author
POST http://localhost:8080/api/v1/authors
Authorization: Bearer PASTE_YOUR_TOKEN_HERE
Content-Type: application/json

{
  "name": "Nauke"
}

### Delete Author with their Books
DELETE http://localhost:8080/api/v1/authors/1
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Update Author name
PATCH http://localhost:8080/api/v1/authors/3
Authorization: Bearer PASTE_YOUR_TOKEN_HERE
Content-Type: application/json

{
  "name": "Rouven"
}


###Books
### Get all Books
GET http://localhost:8080/api/v1/books
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Get single Books
GET http://localhost:8080/api/v1/books/1
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Get all Book names
GET http://localhost:8080/api/v1/books/all
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Get title through ISBN
GET http://localhost:8080/api/v1/books/findISBN?title=How%20to%20be%20arbeitslos
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Create a new Book
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "title": "bester Mann",
  "isbn": "123-67",
  "authorId": 2
  
}

### Delete Book (Author stays)
DELETE http://localhost:8080/api/v1/books/4
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Security
### Register an account
Post http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Rouven",
  "lastName": "Nauke",
  "email": "RouvenNauke@example.com",
  "password": "passwort"
}

### Authenticate an Account
Post http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "RouvenNauke@example.com",
  "password": "passwort"
}