

### Autoren
### Alle Autoren mit ihren Werken
GET http://localhost:8080/api/v1/authors/books
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJSb3V2ZW5OYXVrZUBleGFtcGxlLmNvbSIsImlhdCI6MTc3NTE0MDQ4MywiZXhwIjoxNzc1MTQxOTIzfQ.Vx1toayxow26xps8NKyvp79y9ztTE15B4OResZ57Ktk

### Einzelne Autoren mit ihren Werken
GET http://localhost:8080/api/v1/authors/1/books
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Alle Autoren ohne ihre Werke
GET http://localhost:8080/api/v1/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJSb3V2ZW5OYXVrZUBleGFtcGxlLmNvbSIsImlhdCI6MTc3NTE0MDQ4MywiZXhwIjoxNzc1MTQxOTIzfQ.Vx1toayxow26xps8NKyvp79y9ztTE15B4OResZ57Ktk


### Einzelne Autoren ohne ihre Werke
GET http://localhost:8080/api/v1/authors/2
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Autor erstellen
POST http://localhost:8080/api/v1/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJSb3V2ZW5OYXVrZUBleGFtcGxlLmNvbSIsImlhdCI6MTc3NTE0MDQ4MywiZXhwIjoxNzc1MTQxOTIzfQ.Vx1toayxow26xps8NKyvp79y9ztTE15B4OResZ57Ktk
Content-Type: application/json

{
  "name": "Nauke"
}

### Autor mit all seinen Büchern löschen
DELETE http://localhost:8080/api/v1/authors/1
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Autor und alle seine Bücher löschen
DELETE http://localhost:8080/api/v1/authors
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Update Author name
PATCH http://localhost:8080/api/v1/authors/3
Authorization: Bearer PASTE_YOUR_TOKEN_HERE
Content-Type: application/json

{
  "name": "Rouven"
}


###Books
### Get all Books
GET http://localhost:8080/api/v1/books
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Get single Books
GET http://localhost:8080/api/v1/books/1
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Alle vorhanden Büchertitel ausgeben
GET http://localhost:8080/api/v1/books/all
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### ISBN durch Titel herausbekommen
GET http://localhost:8080/api/v1/books/findISBN?title=How%20to%20be%20arbeitslos
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Neues Buch anlegen
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "title": "bester Mann",
  "isbn": "123-67",
  "authorId": 2
  
}

### Buch Löschen, Autor bleibt
DELETE http://localhost:8080/api/v1/books/4
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### Security
### Register an account
Post http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Rouven",
  "lastName": "Nauke",
  "email": "RouvenNauke@example.com",
  "password": "passwort"
}

### Authenticate an Account
Post http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "RouvenNauke@example.com",
  "password": "passwort"
}